// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using assignment_1.Data;

#nullable disable

namespace assignment_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("assignment_1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Online educational seminars and presentations",
                            Name = "Webinar"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Live music performances and shows",
                            Name = "Concert"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Interactive skill-building sessions",
                            Name = "Workshop"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Professional gatherings and networking events",
                            Name = "Conference"
                        });
                });

            modelBuilder.Entity("assignment_1.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            AvailableTickets = 100,
                            CategoryId = 1,
                            DateTime = new DateTime(2025, 10, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 29.99m,
                            Title = "Introduction to ASP.NET Core"
                        },
                        new
                        {
                            EventId = 2,
                            AvailableTickets = 500,
                            CategoryId = 2,
                            DateTime = new DateTime(2025, 11, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 89.99m,
                            Title = "Rock Festival 2025"
                        },
                        new
                        {
                            EventId = 3,
                            AvailableTickets = 50,
                            CategoryId = 3,
                            DateTime = new DateTime(2025, 10, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 49.99m,
                            Title = "Advanced C# Programming"
                        },
                        new
                        {
                            EventId = 4,
                            AvailableTickets = 200,
                            CategoryId = 4,
                            DateTime = new DateTime(2025, 12, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 199.99m,
                            Title = "Tech Summit 2025"
                        },
                        new
                        {
                            EventId = 5,
                            AvailableTickets = 3,
                            CategoryId = 2,
                            DateTime = new DateTime(2025, 10, 25, 20, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 59.99m,
                            Title = "Jazz Night Live"
                        },
                        new
                        {
                            EventId = 6,
                            AvailableTickets = 2,
                            CategoryId = 3,
                            DateTime = new DateTime(2025, 11, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 299.99m,
                            Title = "Web Development Bootcamp"
                        },
                        new
                        {
                            EventId = 7,
                            AvailableTickets = 0,
                            CategoryId = 3,
                            DateTime = new DateTime(2025, 10, 18, 13, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 39.99m,
                            Title = "Database Design Workshop"
                        },
                        new
                        {
                            EventId = 8,
                            AvailableTickets = 150,
                            CategoryId = 1,
                            DateTime = new DateTime(2025, 11, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 19.99m,
                            Title = "Virtual Reality in Education"
                        });
                });

            modelBuilder.Entity("assignment_1.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseId"));

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("assignment_1.Models.PurchaseItem", b =>
                {
                    b.Property<int>("PurchaseItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseItemId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerTicket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PurchaseItemId");

                    b.HasIndex("EventId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("assignment_1.Models.Event", b =>
                {
                    b.HasOne("assignment_1.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("assignment_1.Models.PurchaseItem", b =>
                {
                    b.HasOne("assignment_1.Models.Event", "Event")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("assignment_1.Models.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("assignment_1.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("assignment_1.Models.Event", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("assignment_1.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
